services:
  keycloak:
    container_name: luxus-connect-keycloak-ctnr
    image: quay.io/keycloak/keycloak:latest
    command: start
    env_file:
      - ./docker/test/keycloak/.keycloak.env
    depends_on:
      - database
    networks:
      - default-dev-net
    ports:
      - "8080:8080"

  database:
    container_name: luxus-connect-database-dev-ctnr
    image: luxus/luxus-connect-database-dev:latest
    build:
      context: .
      dockerfile: ./docker/test/database/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./docker/test/database/.database.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - "5001:5001"
    networks:
      - default-dev-net
    restart: unless-stopped

networks:
  default-dev-net:
    driver: bridge

volumes:
  postgresql-data:
