/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProviderPlanServiceResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type boolean
   */
  active: boolean;
  /**
   * @type boolean
   */
  recurring: boolean;
  /**
   * @type null,number, decimal
   */
  price: number | null;
  /**
   * @type null,string
   */
  service_type?: string | null;
  /**
   * @type null,string
   */
  invoice_name?: string | null;
  /**
   * @type null,string
   */
  application_type?: string | null;
  /**
   * @type null,string
   */
  availability_rule?: string | null;
  /**
   * @type null,string
   */
  exclusive_customer_id?: string | null;
  /**
   * @type null,string
   */
  exclusive_customer_name?: string | null;
};
