/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateCustomerInput = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type null,string
   */
  legal_name?: string | null;
  /**
   * @type null,string
   */
  state_registration?: string | null;
  /**
   * @type null,string, date
   */
  birth_or_opening_date?: string | null;
  /**
   * @type null,string
   */
  responsible_salesperson_user_id?: string | null;
  /**
   * @type null,string
   */
  billing_email?: string | null;
  /**
   * @type null,boolean
   */
  is_reseller?: boolean | null;
  /**
   * @type null,string, date
   */
  commercial_activation_date?: string | null;
  /**
   * @type null,string
   */
  contracted_luxus_cnpj?: string | null;
};
