/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as _appLayoutRouteImport } from './pages/__app/layout'
import { Route as _appIndexRouteImport } from './pages/__app/index'
import { Route as _appStockIndexRouteImport } from './pages/__app/stock/index'
import { Route as _appSettingsIndexRouteImport } from './pages/__app/settings/index'
import { Route as _appProvidersIndexRouteImport } from './pages/__app/providers/index'
import { Route as _appProcessingMonthsIndexRouteImport } from './pages/__app/processing-months/index'
import { Route as _appPhoneLinesIndexRouteImport } from './pages/__app/phone-lines/index'
import { Route as _appInvoicesIndexRouteImport } from './pages/__app/invoices/index'
import { Route as _appCustomersIndexRouteImport } from './pages/__app/customers/index'
import { Route as _appBillingCyclesIndexRouteImport } from './pages/__app/billing-cycles/index'
import { Route as _appStockPhoneLineIdRouteImport } from './pages/__app/stock/$phoneLineId'
import { Route as _appProvidersProviderIdRouteImport } from './pages/__app/providers/$providerId'
import { Route as _appProcessingMonthsProcessingMonthIdRouteImport } from './pages/__app/processing-months/$processingMonthId'
import { Route as _appPhoneLinesPhoneLineIdRouteImport } from './pages/__app/phone-lines/$phoneLineId'
import { Route as _appInvoicesInvoiceIdRouteImport } from './pages/__app/invoices/$invoiceId'
import { Route as _appCustomersCustomerIdRouteImport } from './pages/__app/customers/$customerId'
import { Route as _appBillingCyclesCycleIdRouteImport } from './pages/__app/billing-cycles/$cycleId'
import { Route as _appReportsTransitionPendingIndexRouteImport } from './pages/__app/reports/transition-pending/index'

const _appLayoutRoute = _appLayoutRouteImport.update({
  id: '/__app',
  getParentRoute: () => rootRouteImport,
} as any)
const _appIndexRoute = _appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appStockIndexRoute = _appStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appSettingsIndexRoute = _appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appProvidersIndexRoute = _appProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appProcessingMonthsIndexRoute =
  _appProcessingMonthsIndexRouteImport.update({
    id: '/processing-months/',
    path: '/processing-months/',
    getParentRoute: () => _appLayoutRoute,
  } as any)
const _appPhoneLinesIndexRoute = _appPhoneLinesIndexRouteImport.update({
  id: '/phone-lines/',
  path: '/phone-lines/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appInvoicesIndexRoute = _appInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appCustomersIndexRoute = _appCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appBillingCyclesIndexRoute = _appBillingCyclesIndexRouteImport.update({
  id: '/billing-cycles/',
  path: '/billing-cycles/',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appStockPhoneLineIdRoute = _appStockPhoneLineIdRouteImport.update({
  id: '/stock/$phoneLineId',
  path: '/stock/$phoneLineId',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appProvidersProviderIdRoute = _appProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appProcessingMonthsProcessingMonthIdRoute =
  _appProcessingMonthsProcessingMonthIdRouteImport.update({
    id: '/processing-months/$processingMonthId',
    path: '/processing-months/$processingMonthId',
    getParentRoute: () => _appLayoutRoute,
  } as any)
const _appPhoneLinesPhoneLineIdRoute =
  _appPhoneLinesPhoneLineIdRouteImport.update({
    id: '/phone-lines/$phoneLineId',
    path: '/phone-lines/$phoneLineId',
    getParentRoute: () => _appLayoutRoute,
  } as any)
const _appInvoicesInvoiceIdRoute = _appInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appCustomersCustomerIdRoute = _appCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => _appLayoutRoute,
} as any)
const _appBillingCyclesCycleIdRoute =
  _appBillingCyclesCycleIdRouteImport.update({
    id: '/billing-cycles/$cycleId',
    path: '/billing-cycles/$cycleId',
    getParentRoute: () => _appLayoutRoute,
  } as any)
const _appReportsTransitionPendingIndexRoute =
  _appReportsTransitionPendingIndexRouteImport.update({
    id: '/reports/transition-pending/',
    path: '/reports/transition-pending/',
    getParentRoute: () => _appLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _appIndexRoute
  '/billing-cycles/$cycleId': typeof _appBillingCyclesCycleIdRoute
  '/customers/$customerId': typeof _appCustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof _appInvoicesInvoiceIdRoute
  '/phone-lines/$phoneLineId': typeof _appPhoneLinesPhoneLineIdRoute
  '/processing-months/$processingMonthId': typeof _appProcessingMonthsProcessingMonthIdRoute
  '/providers/$providerId': typeof _appProvidersProviderIdRoute
  '/stock/$phoneLineId': typeof _appStockPhoneLineIdRoute
  '/billing-cycles/': typeof _appBillingCyclesIndexRoute
  '/customers/': typeof _appCustomersIndexRoute
  '/invoices/': typeof _appInvoicesIndexRoute
  '/phone-lines/': typeof _appPhoneLinesIndexRoute
  '/processing-months/': typeof _appProcessingMonthsIndexRoute
  '/providers/': typeof _appProvidersIndexRoute
  '/settings/': typeof _appSettingsIndexRoute
  '/stock/': typeof _appStockIndexRoute
  '/reports/transition-pending/': typeof _appReportsTransitionPendingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _appIndexRoute
  '/billing-cycles/$cycleId': typeof _appBillingCyclesCycleIdRoute
  '/customers/$customerId': typeof _appCustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof _appInvoicesInvoiceIdRoute
  '/phone-lines/$phoneLineId': typeof _appPhoneLinesPhoneLineIdRoute
  '/processing-months/$processingMonthId': typeof _appProcessingMonthsProcessingMonthIdRoute
  '/providers/$providerId': typeof _appProvidersProviderIdRoute
  '/stock/$phoneLineId': typeof _appStockPhoneLineIdRoute
  '/billing-cycles': typeof _appBillingCyclesIndexRoute
  '/customers': typeof _appCustomersIndexRoute
  '/invoices': typeof _appInvoicesIndexRoute
  '/phone-lines': typeof _appPhoneLinesIndexRoute
  '/processing-months': typeof _appProcessingMonthsIndexRoute
  '/providers': typeof _appProvidersIndexRoute
  '/settings': typeof _appSettingsIndexRoute
  '/stock': typeof _appStockIndexRoute
  '/reports/transition-pending': typeof _appReportsTransitionPendingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__app': typeof _appLayoutRouteWithChildren
  '/__app/': typeof _appIndexRoute
  '/__app/billing-cycles/$cycleId': typeof _appBillingCyclesCycleIdRoute
  '/__app/customers/$customerId': typeof _appCustomersCustomerIdRoute
  '/__app/invoices/$invoiceId': typeof _appInvoicesInvoiceIdRoute
  '/__app/phone-lines/$phoneLineId': typeof _appPhoneLinesPhoneLineIdRoute
  '/__app/processing-months/$processingMonthId': typeof _appProcessingMonthsProcessingMonthIdRoute
  '/__app/providers/$providerId': typeof _appProvidersProviderIdRoute
  '/__app/stock/$phoneLineId': typeof _appStockPhoneLineIdRoute
  '/__app/billing-cycles/': typeof _appBillingCyclesIndexRoute
  '/__app/customers/': typeof _appCustomersIndexRoute
  '/__app/invoices/': typeof _appInvoicesIndexRoute
  '/__app/phone-lines/': typeof _appPhoneLinesIndexRoute
  '/__app/processing-months/': typeof _appProcessingMonthsIndexRoute
  '/__app/providers/': typeof _appProvidersIndexRoute
  '/__app/settings/': typeof _appSettingsIndexRoute
  '/__app/stock/': typeof _appStockIndexRoute
  '/__app/reports/transition-pending/': typeof _appReportsTransitionPendingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing-cycles/$cycleId'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/phone-lines/$phoneLineId'
    | '/processing-months/$processingMonthId'
    | '/providers/$providerId'
    | '/stock/$phoneLineId'
    | '/billing-cycles/'
    | '/customers/'
    | '/invoices/'
    | '/phone-lines/'
    | '/processing-months/'
    | '/providers/'
    | '/settings/'
    | '/stock/'
    | '/reports/transition-pending/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing-cycles/$cycleId'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/phone-lines/$phoneLineId'
    | '/processing-months/$processingMonthId'
    | '/providers/$providerId'
    | '/stock/$phoneLineId'
    | '/billing-cycles'
    | '/customers'
    | '/invoices'
    | '/phone-lines'
    | '/processing-months'
    | '/providers'
    | '/settings'
    | '/stock'
    | '/reports/transition-pending'
  id:
    | '__root__'
    | '/__app'
    | '/__app/'
    | '/__app/billing-cycles/$cycleId'
    | '/__app/customers/$customerId'
    | '/__app/invoices/$invoiceId'
    | '/__app/phone-lines/$phoneLineId'
    | '/__app/processing-months/$processingMonthId'
    | '/__app/providers/$providerId'
    | '/__app/stock/$phoneLineId'
    | '/__app/billing-cycles/'
    | '/__app/customers/'
    | '/__app/invoices/'
    | '/__app/phone-lines/'
    | '/__app/processing-months/'
    | '/__app/providers/'
    | '/__app/settings/'
    | '/__app/stock/'
    | '/__app/reports/transition-pending/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _appLayoutRoute: typeof _appLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app/': {
      id: '/__app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _appIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/stock/': {
      id: '/__app/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof _appStockIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/settings/': {
      id: '/__app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof _appSettingsIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/providers/': {
      id: '/__app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof _appProvidersIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/processing-months/': {
      id: '/__app/processing-months/'
      path: '/processing-months'
      fullPath: '/processing-months/'
      preLoaderRoute: typeof _appProcessingMonthsIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/phone-lines/': {
      id: '/__app/phone-lines/'
      path: '/phone-lines'
      fullPath: '/phone-lines/'
      preLoaderRoute: typeof _appPhoneLinesIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/invoices/': {
      id: '/__app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof _appInvoicesIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/customers/': {
      id: '/__app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof _appCustomersIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/billing-cycles/': {
      id: '/__app/billing-cycles/'
      path: '/billing-cycles'
      fullPath: '/billing-cycles/'
      preLoaderRoute: typeof _appBillingCyclesIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/stock/$phoneLineId': {
      id: '/__app/stock/$phoneLineId'
      path: '/stock/$phoneLineId'
      fullPath: '/stock/$phoneLineId'
      preLoaderRoute: typeof _appStockPhoneLineIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/providers/$providerId': {
      id: '/__app/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof _appProvidersProviderIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/processing-months/$processingMonthId': {
      id: '/__app/processing-months/$processingMonthId'
      path: '/processing-months/$processingMonthId'
      fullPath: '/processing-months/$processingMonthId'
      preLoaderRoute: typeof _appProcessingMonthsProcessingMonthIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/phone-lines/$phoneLineId': {
      id: '/__app/phone-lines/$phoneLineId'
      path: '/phone-lines/$phoneLineId'
      fullPath: '/phone-lines/$phoneLineId'
      preLoaderRoute: typeof _appPhoneLinesPhoneLineIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/invoices/$invoiceId': {
      id: '/__app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof _appInvoicesInvoiceIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/customers/$customerId': {
      id: '/__app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof _appCustomersCustomerIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/billing-cycles/$cycleId': {
      id: '/__app/billing-cycles/$cycleId'
      path: '/billing-cycles/$cycleId'
      fullPath: '/billing-cycles/$cycleId'
      preLoaderRoute: typeof _appBillingCyclesCycleIdRouteImport
      parentRoute: typeof _appLayoutRoute
    }
    '/__app/reports/transition-pending/': {
      id: '/__app/reports/transition-pending/'
      path: '/reports/transition-pending'
      fullPath: '/reports/transition-pending/'
      preLoaderRoute: typeof _appReportsTransitionPendingIndexRouteImport
      parentRoute: typeof _appLayoutRoute
    }
  }
}

interface _appLayoutRouteChildren {
  _appIndexRoute: typeof _appIndexRoute
  _appBillingCyclesCycleIdRoute: typeof _appBillingCyclesCycleIdRoute
  _appCustomersCustomerIdRoute: typeof _appCustomersCustomerIdRoute
  _appInvoicesInvoiceIdRoute: typeof _appInvoicesInvoiceIdRoute
  _appPhoneLinesPhoneLineIdRoute: typeof _appPhoneLinesPhoneLineIdRoute
  _appProcessingMonthsProcessingMonthIdRoute: typeof _appProcessingMonthsProcessingMonthIdRoute
  _appProvidersProviderIdRoute: typeof _appProvidersProviderIdRoute
  _appStockPhoneLineIdRoute: typeof _appStockPhoneLineIdRoute
  _appBillingCyclesIndexRoute: typeof _appBillingCyclesIndexRoute
  _appCustomersIndexRoute: typeof _appCustomersIndexRoute
  _appInvoicesIndexRoute: typeof _appInvoicesIndexRoute
  _appPhoneLinesIndexRoute: typeof _appPhoneLinesIndexRoute
  _appProcessingMonthsIndexRoute: typeof _appProcessingMonthsIndexRoute
  _appProvidersIndexRoute: typeof _appProvidersIndexRoute
  _appSettingsIndexRoute: typeof _appSettingsIndexRoute
  _appStockIndexRoute: typeof _appStockIndexRoute
  _appReportsTransitionPendingIndexRoute: typeof _appReportsTransitionPendingIndexRoute
}

const _appLayoutRouteChildren: _appLayoutRouteChildren = {
  _appIndexRoute: _appIndexRoute,
  _appBillingCyclesCycleIdRoute: _appBillingCyclesCycleIdRoute,
  _appCustomersCustomerIdRoute: _appCustomersCustomerIdRoute,
  _appInvoicesInvoiceIdRoute: _appInvoicesInvoiceIdRoute,
  _appPhoneLinesPhoneLineIdRoute: _appPhoneLinesPhoneLineIdRoute,
  _appProcessingMonthsProcessingMonthIdRoute:
    _appProcessingMonthsProcessingMonthIdRoute,
  _appProvidersProviderIdRoute: _appProvidersProviderIdRoute,
  _appStockPhoneLineIdRoute: _appStockPhoneLineIdRoute,
  _appBillingCyclesIndexRoute: _appBillingCyclesIndexRoute,
  _appCustomersIndexRoute: _appCustomersIndexRoute,
  _appInvoicesIndexRoute: _appInvoicesIndexRoute,
  _appPhoneLinesIndexRoute: _appPhoneLinesIndexRoute,
  _appProcessingMonthsIndexRoute: _appProcessingMonthsIndexRoute,
  _appProvidersIndexRoute: _appProvidersIndexRoute,
  _appSettingsIndexRoute: _appSettingsIndexRoute,
  _appStockIndexRoute: _appStockIndexRoute,
  _appReportsTransitionPendingIndexRoute:
    _appReportsTransitionPendingIndexRoute,
}

const _appLayoutRouteWithChildren = _appLayoutRoute._addFileChildren(
  _appLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _appLayoutRoute: _appLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
