// <auto-generated />
using Luxus.Connect.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luxus.Connect.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411052212_00")]
    partial class _00
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing_cycle_status", new[] { "closed", "open" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "customer_document_type", new[] { "cnh", "cnpj", "cpf", "municipal_registration", "other", "rg", "state_registration" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "customer_type", new[] { "pf", "pj" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exceedance_charge_type", new[] { "mirroed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invoice_item_unit", new[] { "gb", "kb", "mb", "min", "sms", "tb" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "line_classification", new[] { "dependent", "normal", "other", "titular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "phone_line_status", new[] { "active", "awaiting_invoice", "cancelled", "in_stock", "in_transition", "inactive", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "provider_invoice_item_type", new[] { "discount", "extra_detail", "extra_header", "extra_location", "other", "plan", "service", "usage" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "provider_invoice_status", new[] { "cancelled", "draft", "overdue", "paid", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_application_type", new[] { "addon", "plan", "service" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_availability_rule", new[] { "always", "custom", "cycle_only" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_type", new[] { "data", "other", "roaming", "sms", "subscription" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transition_sub_status", new[] { "none", "pending_activation", "pending_cancellation", "pending_portability", "pending_pp", "pending_tt" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
