// <auto-generated />
using System;
using Luxus.Connect.Domain.BillingCycles.Aggregates;
using Luxus.Connect.Domain.Customers.Aggregates;
using Luxus.Connect.Domain.PhoneLines.Aggregates;
using Luxus.Connect.Domain.ProcessingMonths.Aggregates;
using Luxus.Connect.Domain.Providers.Enums;
using Luxus.Connect.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luxus.Connect.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414150020_07")]
    partial class _07
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing_cycle_status", new[] { "closed", "open" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "customer_document_type", new[] { "cnh", "cnpj", "cpf", "municipal_registration", "other", "rg", "state_registration" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "customer_type", new[] { "pf", "pj" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exceedance_charge_type", new[] { "mirroed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invoice_item_unit", new[] { "gb", "kb", "mb", "min", "sms", "tb" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "line_classification", new[] { "dependent", "normal", "other", "titular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "phone_line_status", new[] { "active", "awaiting_invoice", "cancelled", "in_stock", "in_transition", "inactive", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "processing_month_status", new[] { "closed", "open" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "provider_invoice_item_type", new[] { "discount", "extra_detail", "extra_header", "extra_location", "other", "plan", "service", "usage" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "provider_invoice_status", new[] { "cancelled", "draft", "overdue", "paid", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_application_type", new[] { "addon", "plan", "service" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_availability_rule", new[] { "always", "custom", "cycle_only" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_type", new[] { "data", "other", "roaming", "sms", "subscription" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transition_sub_status", new[] { "none", "pending_activation", "pending_cancellation", "pending_portability", "pending_pp", "pending_tt" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingCycleProviderAccount", b =>
                {
                    b.Property<string>("BillingCyclesId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderAccountsId")
                        .HasColumnType("character varying(36)");

                    b.HasKey("BillingCyclesId", "ProviderAccountsId");

                    b.HasIndex("ProviderAccountsId");

                    b.ToTable("BillingCycleProviderAccounts", (string)null);
                });

            modelBuilder.Entity("Goal.Infra.Data.Auditing.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityName");

                    b.HasIndex("EntityName", "ChangedBy");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.BillingCycles.Aggregates.BillingCycle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<BillingCycleStatus>("Status")
                        .HasColumnType("billing_cycle_status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("BillingCycles", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Controllership.Aggregates.CostCenter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("CostCenters", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("BirthOrOpeningDate")
                        .HasColumnType("date");

                    b.Property<string>("LegalName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<CustomerType>("Type")
                        .HasColumnType("customer_type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("OrganizationId", "ProviderId", "LegalName")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ProviderId", "Name")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.CustomerAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Complement")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.CustomerDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<CustomerDocumentType>("DocumentType")
                        .HasColumnType("customer_document_type");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentType");

                    b.ToTable("CustomerDocuments", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.CustomerProcessingMonthManualRelease", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProcessingMonthId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleasedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProcessingMonthId");

                    b.HasIndex("CustomerId", "ProcessingMonthId")
                        .IsUnique();

                    b.ToTable("CustomerProcessingMonthManualReleases", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateOnly?>("ActivationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CancellationDate")
                        .HasColumnType("date");

                    b.Property<string>("CostCenterId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("LastInvoiceId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<LineClassification>("LineClassification")
                        .HasColumnType("line_classification");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderPlanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<PhoneLineStatus>("Status")
                        .HasColumnType("phone_line_status");

                    b.Property<string>("TitularLineId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset?>("TransitionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TransitionSubStatus?>("TransitionSubStatus")
                        .HasColumnType("transition_sub_status");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("LastInvoiceId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ProviderAccountId");

                    b.HasIndex("ProviderPlanId");

                    b.HasIndex("TitularLineId");

                    b.HasIndex("Status", "TransitionStartedAt");

                    b.ToTable("PhoneLines", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLineCustomerLink", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneLineId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PhoneLineId")
                        .IsUnique()
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("PhoneLineId", "StartDate");

                    b.ToTable("PhoneLineCustomerLinks", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLineService", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneLineId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProviderPlanServiceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Recurring")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProviderPlanServiceId");

                    b.HasIndex("PhoneLineId", "ProviderPlanServiceId")
                        .IsUnique();

                    b.ToTable("PhoneLineServices", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.ProcessingMonths.Aggregates.ProcessingMonth", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("ClosedInContingency")
                        .HasColumnType("boolean");

                    b.Property<string>("ContingencyJustification")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<ProcessingMonthStatus>("Status")
                        .HasColumnType("processing_month_status");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("OrganizationId", "ProviderId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ProcessingMonths", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ContractingCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "TaxId")
                        .IsUnique();

                    b.ToTable("ContractingCompanies", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.Provider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Active");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContractingCompanyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("ContractingCompanyId", "AccountNumber")
                        .IsUnique();

                    b.ToTable("ProviderAccounts", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("BillingCycleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ContractingCompanyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("CostCenterId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentInvoiceId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProcessingMonthId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<ProviderInvoiceStatus>("Status")
                        .HasColumnType("provider_invoice_status");

                    b.Property<decimal>("SubtotalDiscounts")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SubtotalInstallments")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SubtotalServices")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SubtotalTaxes")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SubtotalUsage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillingCycleId");

                    b.HasIndex("ContractingCompanyId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("ParentInvoiceId");

                    b.HasIndex("ProcessingMonthId");

                    b.HasIndex("ProviderAccountId", "ContractingCompanyId", "ProcessingMonthId", "DueDate")
                        .IsUnique();

                    b.ToTable("ProviderInvoices", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceImportRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Error")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProcessingMonthId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StorageObjectKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProcessingMonthId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("OrganizationId", "ProviderId");

                    b.ToTable("ProviderInvoiceImportRequests", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal?>("ConsumedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<ProviderInvoiceItemType>("ItemType")
                        .HasColumnType("provider_invoice_item_type");

                    b.Property<string>("ParentId")
                        .HasColumnType("character varying(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("QuotaAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<InvoiceItemUnit?>("Unit")
                        .HasColumnType("invoice_item_unit");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ParentId");

                    b.ToTable("ProviderInvoiceItems", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceQuotaSharing", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal?>("ConsumedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("PhoneLineId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PhoneLineId");

                    b.ToTable("ProviderInvoiceQuotaSharing", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceService", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal?>("ConsumedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("QuotaAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<InvoiceItemUnit?>("Unit")
                        .HasColumnType("invoice_item_unit");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PlanId");

                    b.ToTable("ProviderInvoiceServices", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Code")
                        .IsUnique();

                    b.ToTable("ProviderPlans", (string)null);
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlanService", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProviderPlanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Recurring")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProviderPlanId");

                    b.ToTable("ProviderPlanServices", (string)null);
                });

            modelBuilder.Entity("PhoneLineProviderInvoice", b =>
                {
                    b.Property<string>("PhoneLinesId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ProviderInvoicesId")
                        .HasColumnType("character varying(36)");

                    b.HasKey("PhoneLinesId", "ProviderInvoicesId");

                    b.HasIndex("ProviderInvoicesId");

                    b.ToTable("ProviderInvoicePhoneLines", (string)null);
                });

            modelBuilder.Entity("BillingCycleProviderAccount", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.BillingCycles.Aggregates.BillingCycle", null)
                        .WithMany()
                        .HasForeignKey("BillingCyclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderAccount", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Luxus.Connect.Domain.BillingCycles.Aggregates.BillingCycle", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.Customer", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.CustomerAddress", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Customers.Aggregates.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.CustomerDocument", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Customers.Aggregates.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.CustomerProcessingMonthManualRelease", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Customers.Aggregates.Customer", "Customer")
                        .WithMany("CustomerProcessingMonthManualReleases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.ProcessingMonths.Aggregates.ProcessingMonth", "ProcessingMonth")
                        .WithMany("CustomerProcessingMonthManualReleases")
                        .HasForeignKey("ProcessingMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProcessingMonth");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Controllership.Aggregates.CostCenter", "CostCenter")
                        .WithMany("PhoneLines")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", "LastInvoice")
                        .WithMany("LastPhoneLines")
                        .HasForeignKey("LastInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderAccount", "ProviderAccount")
                        .WithMany("PhoneLines")
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlan", "ProviderPlan")
                        .WithMany("PhoneLines")
                        .HasForeignKey("ProviderPlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", "TitularLine")
                        .WithMany("ChildrenLines")
                        .HasForeignKey("TitularLineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CostCenter");

                    b.Navigation("LastInvoice");

                    b.Navigation("ProviderAccount");

                    b.Navigation("ProviderPlan");

                    b.Navigation("TitularLine");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLineCustomerLink", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Customers.Aggregates.Customer", "Customer")
                        .WithMany("PhoneLineLinks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", "PhoneLine")
                        .WithMany("CustomerLinks")
                        .HasForeignKey("PhoneLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PhoneLine");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLineService", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", "PhoneLine")
                        .WithMany("PhoneLineServices")
                        .HasForeignKey("PhoneLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlanService", "ProviderPlanService")
                        .WithMany()
                        .HasForeignKey("ProviderPlanServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneLine");

                    b.Navigation("ProviderPlanService");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.ProcessingMonths.Aggregates.ProcessingMonth", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.Provider", "Provider")
                        .WithMany("ProcessingMonths")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ContractingCompany", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.Provider", "Provider")
                        .WithMany("ContractingCompanies")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderAccount", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ContractingCompany", "ContractingCompany")
                        .WithMany("ProviderAccounts")
                        .HasForeignKey("ContractingCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContractingCompany");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.BillingCycles.Aggregates.BillingCycle", "BillingCycle")
                        .WithMany("ProviderInvoices")
                        .HasForeignKey("BillingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ContractingCompany", "ContractingCompany")
                        .WithMany()
                        .HasForeignKey("ContractingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Controllership.Aggregates.CostCenter", "CostCenter")
                        .WithMany("ProviderInvoices")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", "ParentInvoice")
                        .WithMany()
                        .HasForeignKey("ParentInvoiceId");

                    b.HasOne("Luxus.Connect.Domain.ProcessingMonths.Aggregates.ProcessingMonth", "ProcessingMonth")
                        .WithMany("ProviderInvoices")
                        .HasForeignKey("ProcessingMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderAccount", "ProviderAccount")
                        .WithMany("Invoices")
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingCycle");

                    b.Navigation("ContractingCompany");

                    b.Navigation("CostCenter");

                    b.Navigation("ParentInvoice");

                    b.Navigation("ProcessingMonth");

                    b.Navigation("ProviderAccount");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceImportRequest", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.ProcessingMonths.Aggregates.ProcessingMonth", "ProcessingMonth")
                        .WithMany("ProviderInvoiceImportRequests")
                        .HasForeignKey("ProcessingMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.Provider", "Provider")
                        .WithMany("InvoiceImportRequests")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingMonth");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceItem", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", "Invoice")
                        .WithMany("ProviderInvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Invoice");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceQuotaSharing", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", "Invoice")
                        .WithMany("ProviderInvoiceQuotaSharing")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", "PhoneLine")
                        .WithMany("InvoiceQuotaSharings")
                        .HasForeignKey("PhoneLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PhoneLine");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceService", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", "Invoice")
                        .WithMany("ProviderInvoiceServices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlan", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.Provider", "Provider")
                        .WithMany("ProviderPlans")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlanService", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlan", "ProviderPlan")
                        .WithMany("ProviderPlanServices")
                        .HasForeignKey("ProviderPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderPlan");
                });

            modelBuilder.Entity("PhoneLineProviderInvoice", b =>
                {
                    b.HasOne("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", null)
                        .WithMany()
                        .HasForeignKey("PhoneLinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", null)
                        .WithMany()
                        .HasForeignKey("ProviderInvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Luxus.Connect.Domain.BillingCycles.Aggregates.BillingCycle", b =>
                {
                    b.Navigation("ProviderInvoices");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Controllership.Aggregates.CostCenter", b =>
                {
                    b.Navigation("PhoneLines");

                    b.Navigation("ProviderInvoices");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Customers.Aggregates.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerProcessingMonthManualReleases");

                    b.Navigation("Documents");

                    b.Navigation("PhoneLineLinks");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.PhoneLines.Aggregates.PhoneLine", b =>
                {
                    b.Navigation("ChildrenLines");

                    b.Navigation("CustomerLinks");

                    b.Navigation("InvoiceQuotaSharings");

                    b.Navigation("PhoneLineServices");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.ProcessingMonths.Aggregates.ProcessingMonth", b =>
                {
                    b.Navigation("CustomerProcessingMonthManualReleases");

                    b.Navigation("ProviderInvoiceImportRequests");

                    b.Navigation("ProviderInvoices");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ContractingCompany", b =>
                {
                    b.Navigation("ProviderAccounts");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.Provider", b =>
                {
                    b.Navigation("ContractingCompanies");

                    b.Navigation("InvoiceImportRequests");

                    b.Navigation("ProcessingMonths");

                    b.Navigation("ProviderPlans");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderAccount", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PhoneLines");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoice", b =>
                {
                    b.Navigation("LastPhoneLines");

                    b.Navigation("ProviderInvoiceItems");

                    b.Navigation("ProviderInvoiceQuotaSharing");

                    b.Navigation("ProviderInvoiceServices");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderInvoiceItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Luxus.Connect.Domain.Providers.Aggregates.ProviderPlan", b =>
                {
                    b.Navigation("PhoneLines");

                    b.Navigation("ProviderPlanServices");
                });
#pragma warning restore 612, 618
        }
    }
}
