using Luxus.Connect.Infra.Crosscutting.TextParsing;

namespace Luxus.Connect.Application.Invoices.ImportInvoice.Parsers.Vivo;

public static partial class VivoTextInvoiceParser
{
    public const string ProviderName = "VIVO";

    public static IEnumerable<object> Parse(string text)
    {
        ArgumentNullException.ThrowIfNull(text);

        FixedWidthTextParser parser = new FixedWidthTextParser { Options = { RecordTypeOffset = 110, RecordTypeLength = 4, } }
            .Parse<Line010DHeader>(r => r.RecordType == "010D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.ReferenceMonth, offset: 205, length: 6)
                .Field(r => r.IssueDate, offset: 229, length: 8, format: "yyyyMMdd")
                .Field(r => r.DueDate, offset: 247, length: 8, format: "yyyyMMdd")
                .Field(r => r.BillingStartDate, offset: 353, length: 8, format: "yyyyMMdd")
                .Field(r => r.BillingEndDate, offset: 361, length: 8, format: "yyyyMMdd")
                .Field(r => r.SubtotalServices, offset: 341, length: 12)
                .Field(r => r.SubtotalUsageExceeded, offset: 372, length: 12)
                .Field(r => r.TotalAmount, offset: 540, length: 12)
                .Field(r => r.FiscalReferenceCode, offset: 1770, length: 13)
            .And()
            .Parse<Line011DCustomer>(r => r.RecordType == "011D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Name, offset: 115, length: 83)
                .Field(r => r.LegalName, offset: 199, length: 94)
                .Field(r => r.Document, offset: 1846, length: 18)
                .Field(r => r.Street, offset: 958, length: 19)
                .Field(r => r.Number, offset: 1090, length: 44)
                .Field(r => r.Neighborhood, offset: 1039, length: 52)
                .Field(r => r.ZipCode, offset: 558, length: 9)
                .Field(r => r.City, offset: 977, length: 61)
                .Field(r => r.State, offset: 1134, length: 159)
                .Field(r => r.Country, offset: 1293, length: 135)
                .Field(r => r.StateRegistration, offset: 876, length: 32)
            .And()
            .Parse<Line020DPayment>(r => r.RecordType == "020D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.DigitableLine, offset: 178, length: 51)
                .Field(r => r.PixQrCode, offset: 488, length: 999)
            .And()
            .Parse<Line014DFiscalPlaceholder>(r => r.RecordType == "014D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Payload, offset: 178, length: 1600)
            .And()
            .Parse<Line015DTariffExcessSummary>(r => r.RecordType == "015D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.RawPayload, offset: 178, length: 1600)
            .And()
            .Parse<Line016DPreviousPeriodUsage>(r => r.RecordType == "016D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Quantity, offset: 365, length: 14)
                .Field(r => r.Amount, offset: 379, length: 9)
                .Field(r => r.TariffCode, offset: 398, length: 8)
            .And()
            .Parse<Line017JFiscalMetadata>(r => r.RecordType == "017J")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Payload, offset: 178, length: 1600)
            .And()
            .Parse<Line017DFiscalMetadata>(r => r.RecordType == "017D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Payload, offset: 178, length: 1600)
            .And()
            .Parse<Line050WServicesHeader>(r => r.RecordType == "050W")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.PlanCode, offset: 159, length: 18)
                .Field(r => r.Description, offset: 178, length: 999)
            .And()
            .Parse<Line050IPlanSummary>(r => r.RecordType == "050I")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.PlanCode, offset: 159, length: 19)
                .Field(r => r.PlanName, offset: 178, length: 40)
                .Field(r => r.Subtotal, offset: 230, length: 16)
                .Field(r => r.Flags, offset: 252, length: 10)
            .And()
            .Parse<Line050HService>(r => r.RecordType == "050H")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.PlanCode, offset: 159, length: 19)
                .Field(r => r.ServiceName, offset: 178, length: 41)
                .Field(r => r.Flags, offset: 331, length: 1)
                .Field(r => r.Quantity, offset: 219, length: 10)
                .Field(r => r.Franchise, offset: 229, length: 16)
                .Field(r => r.Used, offset: 261, length: 16)
                .Field(r => r.Unity, offset: 313, length: 4)
                .Field(r => r.Total, offset: 281, length: 18)
            .And()
            .Parse<Line050GService>(r => r.RecordType == "050G")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.PlanCode, offset: 159, length: 19)
                .Field(r => r.ServiceName, offset: 178, length: 41)
                .Field(r => r.Flags, offset: 331, length: 1)
                .Field(r => r.Quantity, offset: 219, length: 10)
                .Field(r => r.Franchise, offset: 229, length: 16)
                .Field(r => r.Used, offset: 261, length: 16)
                .Field(r => r.Unity, offset: 309, length: 4)
                .Field(r => r.Total, offset: 281, length: 18)
            .And()
            .Parse<Line051WUsageHeader>(r => r.RecordType == "051W")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Description, offset: 178, length: 50)
            .And()
            .Parse<Line051DUsage>(r => r.RecordType == "051D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.PlanCode, offset: 159, length: 19)
                .Field(r => r.ServiceName, offset: 178, length: 50)
                .Field(r => r.Unity, offset: 260, length: 4)
                .Field(r => r.Franchise, offset: 228, length: 16)
                .Field(r => r.Used, offset: 244, length: 16)
            .And()
            .Parse<Line052WExtraUsageHeader>(r => r.RecordType == "052W")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Description, offset: 178, length: 100)
                .Field(r => r.FooterFlags, offset: 278, length: 2)
            .And()
            .Parse<Line052EExtraLocation>(r => r.RecordType == "052E")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Location, offset: 178, length: 999)
            .And()
            .Parse<Line052DExtraUsageDetail>(r => r.RecordType == "052D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Description, offset: 178, length: 80)
                .Field(r => r.Quantity, offset: 258, length: 14)
                .Field(r => r.Amount, offset: 272, length: 14)
                .Field(r => r.ServiceCode, offset: 286, length: 10)
            .And()
            .Parse<Line052CExtraSubtotal>(r => r.RecordType == "052C")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Amount, offset: 178, length: 14)
            .And()
            .Parse<Line059AExtraTotal>(r => r.RecordType == "059A")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.TotalAmount, offset: 178, length: 14)
            .And()
            .Parse<InvoiceAccountLinesSummary>(r => r.RecordType == "110T")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.SubtotalServices, offset: 234, length: 10)
            .And()
            .Parse<Line110DAccountLineDetail>(r => r.RecordType == "110D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.LineSequence, offset: 64, length: 6)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.PhoneNumber, offset: 178, length: 70)
                .Field(r => r.PlanName, offset: 248, length: 25)
                .Field(r => r.LineTotal, offset: 318, length: 14)
            .And()
            .Parse<InvoiceFranchiseSectionHeader>(r => r.RecordType == "115T")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.SectionName, offset: 178, length: 54)
                .Field(r => r.TotalsPayload, offset: 232, length: 138)
                .Field(r => r.SectionReference, offset: 370, length: 8)
                .Field(r => r.SubscriberCount, offset: 402, length: 5)
                .Field(r => r.SectionSequence, offset: 408, length: 3)
            .And()
            .Parse<InvoiceFranchiseLineDetail>(r => r.RecordType == "115D")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.ServiceDescription, offset: 182, length: 40)
                .Field(r => r.ServiceOrder, offset: 181, length: 1)
                .Field(r => r.PhoneNumber, offset: 393, length: 14)
                .Field(r => r.DetailSequence, offset: 408, length: 3)
                .Field(r => r.UsageAmount, offset: 222, length: 14)
                .Field(r => r.SectionReference, offset: 65, length: 8)
            .And()
            .Parse<InvoiceFiscalNfcTotals>(r => r.RecordType == "565U")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.FiscalGroupCode, offset: 64, length: 4)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Payload, offset: 145, length: 228)
            .And()
            .Parse<InvoiceFiscalNfcItem>(r => r.RecordType == "565S")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.FiscalGroupCode, offset: 64, length: 4)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.ItemSubqualifier, offset: 124, length: 2)
                .Field(r => r.DetailPayload, offset: 145, length: 319)
            .And()
            .Parse<InvoiceFiscalNfcCustomer>(r => r.RecordType == "565Q")
                .Field(r => r.AccountNumber, offset: 0, length: 10)
                .Field(r => r.BlockNumber, offset: 61, length: 2)
                .Field(r => r.FiscalGroupCode, offset: 64, length: 4)
                .Field(r => r.BlockCode, offset: 84, length: 3)
                .Field(r => r.RecordType, offset: 110, length: 4)
                .Field(r => r.Payload, offset: 145, length: 551)
            .And();

        return parser.DeserializeLines(text);
    }
}
